name: androclient
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.5
  device_info_plus: ^10.1.2
  call_log: ^4.0.0
  flutter_sms_inbox: ^1.0.1
  photo_manager: ^3.2.3
  http: ^1.2.2
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
